### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by kingnobro** [Vrroom/vectorrvnn#2]
Hi, thank you for sharing the code. I'm trying to install the environment but encountering several questions:

1. What is the correct installation order - should I install the Prerequisites first before running `python3 setup.py install --user`?
2. Regarding the Prerequisites:
   - Could you specify which version of PyTorch is required?
   - Could you explain what "EGL" refers to?
3. I haven't been able to test the code yet due to installation issues, but I noticed that while the README mentions `TripletInterface.py` as the main script, I cannot locate this file in the repository. Could you clarify its location?

Thank you for your assistance.

**Comment by kingnobro** [comment]
I also encounter this compilation error:
```shell
   Compiling pathfinder_rasterizer v0.1.0 (/tmp/easy_install-1g639zr5/Vrroom-pathfinder_rasterizer-aab1a72)
error[E0133]: call to unsafe function `khronos_egl::egl1_0::<impl Instance<T>>::get_display` is unsafe and requires unsafe function or block
  --> src/rasterizer.rs:34:23
   |
34 |         let display = egl.get_display(egl::DEFAULT_DISPLAY).expect("display");
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
   |
   = note: consult the function's documentation for information on how to avoid undefined behavior

For more information about this error, try `rustc --explain E0133`.
error: could not compile `pathfinder_rasterizer` (lib) due to 1 previous error
```

**Comment by Vrroom** [comment]
I'm sorry about that. This code is a bit stale. This project didn't get published anywhere, and to be honest, the quality of the grouping is quite unreliable. 

* EGL is used for running a rasterizer. 
* I don't recall the PyTorch version used. 
* TripletInterface.py can be found in this old commit: https://github.com/Vrroom/vectorrvnn/tree/1f80830da9fa7d56d2b68c089f6264060c9e86e3

Again, it might be a waste of your time to get the code running. I mostly use this code-base to maintain a library of utility functions.

If I can help you in any other way, let me know.

**Comment by kingnobro** [comment]
Thanks for your reply. This topic is very interesting, and I plan to set up the testing environment and run some experiments to check their performance.

By the way, I noticed you implemented Fisher's algorithm. Have you found it performs better or worse than your method?

**Comment by Vrroom** [comment]
I'm curious as to why you find this topic interesting. I worked on it for some time and got pretty bored of it. Maybe due to the way I carved out the problem space.

I posted my supplementary material here -- https://github.com/Vrroom/vectorrvnn/issues/1#issuecomment-1399909222 where I show comparison with Fisher et al. 

I would say that both algorithms are not good but sometimes ours behaves more intuitively then theirs given that we try and learn grouping from a manually annotated dataset.

**Comment by kingnobro** [comment]
Okay, thanks for your reply :)

**Comment by Vrroom** [comment]
Let me know about this:

> I'm curious as to why you find this topic interesting. I worked on it for some time and got pretty bored of it. Maybe due to the way I carved out the problem space.

I am genuinely curious how you are planning to approach this problem and to what end.

**Comment by kingnobro** [comment]
I am currently in the idea brainstorming stage. In my last [project](https://aniclipart.github.io/), I discovered that creating layered animations requires manual grouping, which is very tedious.

After seeing your project, I realized that grouped SVG can be used for many other potential applications, which is why this grouping problem is both important and interesting.

**Comment by Vrroom** [comment]
That is a really cool project and congrats. Give me a week or two. I'll try to see if I can make it easy for you to run my code.

**Comment by Vrroom** [comment]
[ReGroup__CVPR_2023_Submission.pdf](https://github.com/user-attachments/files/18083509/ReGroup__CVPR_2023_Submission.pdf)

I have also attached my latest submission as pdf for your reference, if you find anything useful!

**Comment by kingnobro** [comment]
Thanks a lot, I will check it  :)
